# Stage 1: Build
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Nginx
FROM nginx:alpine
# COPY from the build stage using the correct folder
COPY --from=build /app/dist /usr/share/nginx/html
# Copy your custom nginx config
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# Install dependencies using a specific npm registry
RUN npm install --registry=https://registry.npmjs.org
